package com.myspace.patientr;

import java.math.BigDecimal;
import org.drools.core.factmodel.GeneratedFact;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PatientDetails implements java.io.Serializable, GeneratedFact {

	static final long serialVersionUID = 1L;

	private int age;

	private java.lang.Boolean isElligible;

	private java.lang.Boolean firstUser;

	private java.math.BigDecimal billAmt;

	private java.lang.Boolean isInsuredBefore;

	private java.math.BigDecimal feeAmount = java.math.BigDecimal.ZERO;

	private String insuranceCompany;

	public PatientDetails() {
	}

	public java.lang.Boolean getIsElligible() {
		return this.isElligible;
	}

	public void setIsElligible(java.lang.Boolean isElligible) {
		this.isElligible = isElligible;
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public java.lang.Boolean getFirstUser() {
		return this.firstUser;
	}

	public void setFirstUser(java.lang.Boolean firstUser) {
		this.firstUser = firstUser;
	}

	public java.math.BigDecimal getBillAmt() {
		return this.billAmt;
	}

	public void setBillAmt(java.math.BigDecimal billAmt) {
		this.billAmt = billAmt;
	}

	public java.lang.Boolean getIsInsuredBefore() {
		return this.isInsuredBefore;
	}

	public void setIsInsuredBefore(java.lang.Boolean isInsuredBefore) {
		this.isInsuredBefore = isInsuredBefore;
	}

	public java.math.BigDecimal getFeeAmount() {
		return this.feeAmount;
	}

	public void setFeeAmount(java.math.BigDecimal feeAmount) {
		this.feeAmount = feeAmount;
	}

	public java.lang.String getInsuranceCompany() {
		return this.insuranceCompany;
	}

	public void setInsuranceCompany(java.lang.String insuranceCompany) {
		this.insuranceCompany = insuranceCompany;
	}

	public PatientDetails(int age, java.lang.Boolean isElligible,
			java.lang.Boolean firstUser, java.math.BigDecimal billAmt,
			java.lang.Boolean isInsuredBefore, java.math.BigDecimal feeAmount,
			java.lang.String insuranceCompany) {
		this.age = age;
		this.isElligible = isElligible;
		this.firstUser = firstUser;
		this.billAmt = billAmt;
		this.isInsuredBefore = isInsuredBefore;
		this.feeAmount = feeAmount;
		this.insuranceCompany = insuranceCompany;
	}

}