package com.myspace.patientr;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Record implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;
	private java.time.LocalDate admittedOn;

	private java.lang.Boolean isRecordExists;

	public Record() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.time.LocalDate getAdmittedOn() {
		return this.admittedOn;
	}

	public void setAdmittedOn(java.time.LocalDate admittedOn) {
		this.admittedOn = admittedOn;
	}

	public java.lang.Boolean getIsRecordExists() {
		return this.isRecordExists;
	}

	public void setIsRecordExists(java.lang.Boolean isRecordExists) {
		this.isRecordExists = isRecordExists;
	}

	public Record(java.lang.String name, java.time.LocalDate admittedOn,
			java.lang.Boolean isRecordExists) {
		this.name = name;
		this.admittedOn = admittedOn;
		this.isRecordExists = isRecordExists;
	}

}